volumes:
  broker_files: {}
  waitforit: {}

services:
  my-mariadb:
    image: mariadb:10
    restart: always
    env_file: .env
    ports:
      - 8080:8080
      - 3306:3306

  deep_broker:
    image: registry.gitlab.com/antares-at-ncsa/scimma-alerts-integration-demo/deep_broker:latest
    build: ./
    depends_on:
      - my-mariadb
    container_name: deep_broker
    env_file: .env
    command:
      - '/bin/bash'
      - '-c'
      - >
        sleep 5;
        init_tables.py;
        sleep 1;
        gw170817_ingest.py

  gw170817_classifier:
    image: registry.gitlab.com/antares-at-ncsa/scimma-alerts-integration-demo/deep_broker:latest
    build: ./
    depends_on:
      - my-mariadb
      - deep_broker
    container_name: gw170817_classifier
    env_file: .env
    command:
      - '/bin/bash'
      - '-c'
      - >
        sleep 20;
        init_results_table.py;
        sleep 5;
        for ii in {1..10}; do
          sleep 1;
          echo RUNNING CLASSIFIER;
          elcid.py --lim-mag=21.0 --max-num-obs=3000 --skip-every=10 --db-write;
        done

  push-results-to-hop:
    image: registry.gitlab.com/antares-at-ncsa/scimma-alerts-integration-demo/deep_broker:latest
    build: ./
    depends_on:
      - my-mariadb
      - gw170817_classifier
    container_name: push-results-to-hop
    env_file: .env
    command:
      - '/bin/bash'
      - '-c'
      - >
        sleep 50;
        push-results-to-hop.py