version: '3'

networks:
  internal:
    external: false

volumes:
  mariadb: {}
  waitforit: {}
  hopauth: {}

services:
  db:
    image: mariadb:10
    restart: unless-stopped
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
  db-ready:
    image: busybox:1.31
    depends_on:
    - db
    #container_name: alerts-demo-db-check
    volumes:
      - waitforit:/tmp
    command: 
    - 'sh'
    - '-c'
    - 'while ! nc -z db 3306; do sleep 1; printf "-"; done; touch /tmp/db_ready;'
  migration:
    image: registry.gitlab.com/antares-at-ncsa/scimma-alerts-integration-demo/deep_broker:latest
    build: ./
    depends_on:
    - db
    #container_name: alerts-demo-migration
    env_file: .env
    volumes:
      - waitforit:/tmp
    command:
      - '/bin/bash'
      - '-c'
      - >
        while [[ ! -f /tmp/db_ready ]]; do
          echo waiting for database...;
          sleep 2;
        done;
        python init_tables.py && python init_results_table.py && touch /tmp/migration_complete
  init-hop-auth:
    image: ubuntu:20.04
    depends_on:
      - db
      - migration
    command:
      - '/bin/bash'
      - '-c'
      - 'bash /tmp/copy_auth.sh && touch /tmp/hop_auth_ready'
    volumes:
      - waitforit:/tmp
      - hopauth:/home/broker/.config/hop
      - ./auth.toml:/tmp/auth.toml:ro
      - ./copy_auth.sh:/tmp/copy_auth.sh:ro
  source-publisher:
    image: registry.gitlab.com/antares-at-ncsa/scimma-alerts-integration-demo/deep_broker:latest
    build: ./
    depends_on:
      - db
      - migration
    #container_name: alerts-demo-source-publisher
    env_file: .env
    volumes:
      - waitforit:/tmp
      - hopauth:/home/broker/.config/hop
      # - ./broker_files:/home/broker/broker_files
    command:
      - '/bin/bash'
      - '-c'
      - >
        while [[ ! -f /tmp/migration_complete ]]; do
          echo waiting for database migrations...;
          sleep 2;
        done;
        while [[ ! -f /tmp/hop_auth_ready ]]; do
          echo waiting for hop auth provisioning...;
          sleep 2;
        done;
        python publish_source_data.py
  ingest:
    image: registry.gitlab.com/antares-at-ncsa/scimma-alerts-integration-demo/deep_broker:latest
    build: ./
    depends_on:
      - db
      - migration
    #container_name: alerts-demo-ingest
    env_file: .env
    volumes:
      - waitforit:/tmp
      - hopauth:/home/broker/.config/hop
      - ./broker_files:/home/broker/broker_files
    command:
      - '/bin/bash'
      - '-c'
      - >
        while [[ ! -f /tmp/migration_complete ]]; do
          echo waiting for database migrations...;
          sleep 2;
        done;
        while [[ ! -f /tmp/hop_auth_ready ]]; do
          echo waiting for hop auth provisioning...;
          sleep 2;
        done;
        python source_data_ingest.py
  classifier:
    image: registry.gitlab.com/antares-at-ncsa/scimma-alerts-integration-demo/deep_broker:latest
    build: ./
    depends_on:
      - db
      - migration
    #container_name: alerts-demo-classifier
    volumes:
      - waitforit:/tmp
      # - ./broker_files:/home/broker/broker_files
    env_file: .env
    command:
      - '/bin/bash'
      - '-c'
      - >
        while [[ ! -f /tmp/migration_complete ]]; do
          echo waiting for database migrations...;
          sleep 2;
        done;
        echo "Starting classifier..." && python classify.py --lim-mag=21.0 --max-num-obs=3000 --skip-every=10;
