---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-copy-hop-auth
data:
  copy_auth.sh: |
    #!/bin/bash
    set -e
    cp /tmp/auth.toml /home/{{ .Values.securityContext.username }}/.config/hop/auth.toml
    chmod 0600 /home/{{ .Values.securityContext.username }}/.config/hop/auth.toml
    chown {{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.runAsGroup}} /home/{{ .Values.securityContext.username }}/.config/hop/auth.toml
