apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-broker-demo
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-broker-demo
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-broker-demo
    spec:
      volumes:
      containers:
      - name: broker
        image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
        command: ["sleep", "1000"]
