apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-broker-demo
spec:
  replicas: {{ .Values.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-broker-demo
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-broker-demo
    spec:
      containers:
      - name: broker
        image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
        command: ["/bin/bash", "-c", {{ .Values.deployment.image.command | quote }}]
