apiVersion: v2
name: tom-demo
description: SCiMMA TOM demonstration
type: application
version: 0.0.1
dependencies:
- name: postgresql
  version: "11.5.x"
  repository: https://charts.bitnami.com/bitnami
