apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: broker-demo
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: scimma-broker-demo
  project: antares-at-ncsa
  source:
    path: charts/broker
    repoURL: https://github.com/scimma/alert-integration-demo.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
