apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tom-demo
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: scimma-tom-demo
  project: antares-at-ncsa
  source:
    path: charts/tom-demo
    repoURL: https://github.com/scimma/tom-demo.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
