version: '3'

networks:
  internal:
    external: false

volumes:
  postgres: {}
  waitforit: {}
  hopauth: {}

services:
  db:
    image: 'postgres:latest'
    env_file: .env
    ports:
      - 5432:5432
    networks:
      - internal
    volumes:
      - postgres:/var/lib/postgresql
  alert-demo-init-db:
    image: 'postgres:latest'
    env_file: .env
    depends_on:
      - db
    networks:
      - internal
    command:
      - sh
      - -c
      - >
        until pg_isready \
            --username=${POSTGRES_USER} \
            --dbname=${POSTGRES_DB} \
            --host=${DB_HOST} \
            --port=5432;
          do echo waiting for database;
          sleep 2;
          done;
          touch /tmp/db_ready;
    volumes:
      - waitforit:/tmp
  alert-demo-init-django-migrate:
    image: registry.gitlab.com/antares-at-ncsa/scimma-alerts-integration-demo/scimma-tom-demo
    build:
      context: .
    env_file: .env
    depends_on:
      - db
      - alert-demo-init-db
    networks:
      - internal
    command:
      - '/bin/bash'
      - '-c'
      - >
        while [[ ! -f /tmp/db_ready ]]; do
          echo waiting for database...;
          sleep 2;
        done;
        python manage.py migrate && python manage.py makemigrations && touch /tmp/migration_complete
    volumes:
      - ./alerts_demo:/home/worker/alerts_demo
      - waitforit:/tmp
  alert-demo-init-django-createsuperuser:
    image: registry.gitlab.com/antares-at-ncsa/scimma-alerts-integration-demo/scimma-tom-demo
    build:
      context: .
    env_file: .env
    depends_on:
      - db
      - alert-demo-init-db
      - alert-demo-init-django-migrate
    networks:
      - internal
    command:
      - '/bin/bash'
      - '-c'
      - >
        while [[ ! -f /tmp/migration_complete ]]; do
          echo waiting for database migration...;
          sleep 2;
        done;
        bash provisionsuperuser.sh && touch /tmp/superuser_created
    volumes:
      - ./alerts_demo:/home/worker/alerts_demo
      - waitforit:/tmp
  alert-demo-init-hop-auth:
    image: ubuntu:20.04
    depends_on:
      - db
      - alert-demo-init-db
      - alert-demo-init-django-migrate
      - alert-demo-init-django-createsuperuser
    networks:
      - internal
    command:
      - '/bin/bash'
      - '-c'
      - >
        bash /tmp/copy_auth.sh && touch /tmp/hop_auth_ready
    volumes:
      - ./auth.toml:/tmp/auth.toml:ro
      - ./alerts_demo/copy_auth.sh:/tmp/copy_auth.sh:ro
      - waitforit:/tmp
      - hopauth:/home/worker/.config/hop
  alert-demo:
    image: registry.gitlab.com/antares-at-ncsa/scimma-alerts-integration-demo/scimma-tom-demo
    build:
      context: .
    env_file: .env
    depends_on:
      - db
      - alert-demo-init-db
      - alert-demo-init-django-migrate
      - alert-demo-init-django-createsuperuser
    ports:
      - 8000:8000
    networks:
      - internal
    command:
      - '/bin/bash'
      - '-c'
      - >
        while [[ ! -f /tmp/hop_auth_ready ]]; do
          echo waiting for hop_auth_ready...;
          sleep 2;
        done;
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./alerts_demo:/home/worker/alerts_demo
      - waitforit:/tmp
      - hopauth:/home/worker/.config/hop
