classifier:
  replicas: 1
  command: 'echo "Starting classifier..." && python classify.py --lim-mag=21.0 --max-num-obs=3000 --skip-every=10;'
  waitTime: 10
  image:
    repository: "registry.gitlab.com/antares-at-ncsa/scimma-alerts-integration-demo/deep_broker"
    tag: "latest"
    pullPolicy: "Always"
sourceDataPublisher:
  command: "python publish_source_data.py"
  hopUrl: 'kafka://kafka.scimma.org/circuses-demo.alert-integration-source'
sourceDataIngest:
  command: 'python source_data_ingest.py'
  ingestWaitTime: 0.01
alertDataPublisher:
  command: "python publish_broker_alerts.py"
  hopUrl: 'kafka://kafka.scimma.org/circuses-demo.alert-integration-results'

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1006
  runAsGroup: 1003
  username: broker

## ref: https://github.com/bitnami/charts/tree/master/bitnami/mariadb/#installing-the-chart
## ref: https://github.com/helm/charts/blob/master/stable/mariadb/values-production.yaml
mariadb:
  fullnameOverride: "broker-db"
  auth:
    ## The secret has to contain the keys mariadb-root-password, mariadb-replication-password and mariadb-password
    existingSecret: "broker-secrets"
    username: broker
    database: broker
  primary:
    persistence:
      enabled: false
  image:
    debug: false
  volumePermissions:
    enabled: false

